language: ruby
sudo: false
cache: bundler
rvm:
- 2.1.3

install:
  - gem install bundler
  - bundle install --with=distribution

script:
  - '[ ! -z $DANGER_GITHUB_API_TOKEN ] && bundle exec danger || echo "Skipping Danger for External Contributor"'
